CREATE DATABASE demoapp
   LOGFILE GROUP 1 ('/opt/oracle/oradata/demoapp/redo01.log') SIZE 100M,
   MAXLOGFILES 5
   MAXLOGMEMBERS 5
   MAXLOGHISTORY 1
   MAXDATAFILES 100
   MAXINSTANCES 1
   CHARACTER SET US7ASCII
   NATIONAL CHARACTER SET AL16UTF16
   DATAFILE '/opt/oracle/oradata/demoapp/system01.dbf' SIZE 325M REUSE
   EXTENT MANAGEMENT LOCAL
   DEFAULT TEMPORARY TABLESPACE tempts1
      DATAFILE '/opt/oracle/oradata/demoapp/temp01.dbf'
      SIZE 20M REUSE
   UNDO TABLESPACE undotbs
      DATAFILE '/opt/oracle/oradata/demoapp/undotbs01.dbf'
      SIZE 200M REUSE AUTOEXTEND ON NEXT 5120K MAXSIZE UNLIMITED;

CREATE USER demoappuser IDENTIFIED BY "demoapp";

GRANT CONNECT TO demoapp;

GRANT CREATE SESSION GRANT ANY PRIVILEGE TO demoapp;

GRANT UNLIMITED TABLESPACE TO books_admin;
